version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api-development
    restart: on-failure
    volumes:
      - ./api/app:/app/app
      - ./api/public:/app/public
      - ./api/writable:/app/writable
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    restart: on-failure

  nginx:
    restart: on-failure
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
      - ./api/public:/app/public
    ports:
      - 8000:80

networks:
  api-frontend:
    driver: bridge
  api-backend:
    driver: bridge
