version: "3.8"

services:
  api:
    image: registry.alopar.ca/aloparca/api
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.component == api"

  nginx:
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
      - ./api/public:/app/public
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.component == api"

  redis:
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.component == api"

volumes:
  redis-data:

networks:
  api-frontend:
    external: true
  api-backend:
    external: true
