version: "3.8"

# For development and production-specific configuration,
# check out docker-compose.override.yml and docker-compose.prod.yml
# respectively.
services:
  api:
    networks:
      - api-backend
      - api-frontend

  redis:
    image: redis:6-alpine
    networks:
      - api-backend
    command: redis-server --save 120 1 --loglevel warning

  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - api
    networks:
      - api-frontend

networks:
  api-frontend:
    driver: bridge
  api-backend:
    driver: bridge
