version: "3.7"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
      - ./:/app
    ports:
      - 8000:80
