version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/app:/app/app
      - ./api/public:/app/public
      - ./api/writable:/app/writable
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
      - ./api/public:/app/public
    ports:
      - 8000:80
