FROM composer:2 AS composer
WORKDIR /app

COPY composer.json composer.lock ./

# We need to ignore the platform requirements, because the Composer container
# does not come with some of the native extensions that our application requires.
RUN composer install --ignore-platform-reqs

FROM php:8-fpm
WORKDIR /app

COPY --from=composer /app/vendor ./

# Install library requirements
RUN apt update && apt install -y libcurl4-gnutls-dev libxml2-dev

# Install required native extensions
RUN docker-php-ext-install -j$(nproc) curl dom fileinfo

# Install XDebug for application profiling
RUN yes | pecl install xdebug
COPY docker/90-xdebug.ini "$PHP_INI_DIR/conf.d"

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

COPY app/ public/ writable/ ./
